name: Run Crawl Script

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main

jobs:
  run-crawl:
    runs-on: ubuntu-latest
    environment: ai
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Run crawl script
        run: bun update_ai.ts ${{ secrets.AI_LINK_LAST }}

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Run update AI" || echo "No changes to commit"
          git push